name: Master Release
run-name: "Master Release"
on:
  push:
    branches:
      - 'master'

jobs:
  determine-if-deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.tag_exists.outputs.exists  == 'false' }}
      version: ${{ steps.latest_version.outputs.version }}
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # v4.4.0
      with:
        python-version: "3.11"
    - name: Install Changelogger
      run: pip install changelogged==0.11.3
    - name: Get Latest Version
      id: latest_version
      run: |
        VERSION=$(changelogger versions --latest)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
    - uses: mukunku/tag-exists-action@9298fbcc409758ba624a0ae16b83df86637cb8ce # v1.2.0
      id: tag_exists
      with:
        tag: ${{ steps.latest_version.outputs.version }}

  github-tag-and-release:
    runs-on: ubuntu-latest
    needs: determine-if-deploy
    if: needs.determine-if-deploy.outputs.deploy == 'true'
    env:
      ZIP_FILE_NAME: klaviyo_reclaim-${{ needs.determine-if-deploy.outputs.version }}.zip
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: Setup Python 3.11
      uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912 # v4.4.0
      with:
        python-version: '3.11'

    - name: Install Changelogger
      run: pip install changelogged==0.11.3

    - name: Get Changelog Contents
      id: changelog
      run: |
        DELIMITER=$(openssl rand -base64 12)
        VERSION=${{ needs.determine-if-deploy.outputs.version }}
        # Need to capture multiline output in env to preserve newlines
        echo "content<<${DELIMITER}" >> $GITHUB_ENV
        # Add changelog content to the env for release notes
        changelogger notes $VERSION --no-pretty >> $GITHUB_ENV
        echo ${DELIMITER} >> $GITHUB_ENV

    - name: Create Archive
      # Create zip archive for release to composer repository (Packagist)
      run: |
        wrapper_dir="magento2-klaviyo"
        rsync -rc --exclude-from=".distignore" "$GITHUB_WORKSPACE/" $wrapper_dir/ --delete --delete-excluded
        zip -r ${{ env.ZIP_FILE_NAME }} ./$wrapper_dir

    - name: Create GitHub Tag & Release
      # Creates GH tag and release, adds zip archive as artifact to release.
      uses: step-security/release-action@03a57407052f15d1537fd5469a6fbbc536aba326 # v1.20.0
      with:
        tag: ${{ needs.determine-if-deploy.outputs.version }}
        commit: ${{ github.sha }}
        name: Release ${{ needs.determine-if-deploy.outputs.version }}
        body: ${{ env.content }}
        prerelease: true
        artifacts: ${{ env.ZIP_FILE_NAME }}

    - name: Send PagerDuty alert on failure
      if: ${{ failure() }}
      uses: award28/action-pagerduty-alert@504f380bbe87d9787337d1aaac91658040463c7f # 0.4.0
      with:
        pagerduty-integration-key: '${{ secrets.PAGERDUTY_INTEGRATION_KEY }}'
        pagerduty-dedup-key: magento_two_cd

  integration-release:
    runs-on: ubuntu-latest
    needs: [determine-if-deploy, github-tag-and-release]
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
      with:
        egress-policy: audit

    - run: echo "Releasing to Magento2"
    - name: Send PagerDuty alert on failure
      if: ${{ failure() }}
      uses: award28/action-pagerduty-alert@504f380bbe87d9787337d1aaac91658040463c7f # 0.4.0
      with:
        pagerduty-integration-key: '${{ secrets.PAGERDUTY_INTEGRATION_KEY }}'
        pagerduty-dedup-key: magento_two_cd
